source('https://www.rubygems.org')

gem('rspec')
gem('sinatra')
gem('sinatra-contrib', :require => "sinatra/reloader")
gem('sinatra-activerecord')
gem('pg')
gem('rake')
gem('capybara')
gem('pry')
gem('guard')
gem('guard-rspec')
